name: Run getflags.py

on:

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run getflags.py
      run: python getflags.py

    - name: Upload flags.zip
      uses: actions/upload-artifact@v4
      with:
        name: flags
        path: flags.zip
